### ISSUE TITLE
infinit lock

### ISSUE THREAD

**Issue by NOMORECOFFEE** [jeroenrinzema/commander#28]
**Describe the bug**
forget to call wg.Done() and if we call Close() then we are lock on wg.Wait()
https://github.com/jeroenrinzema/commander/blob/master/dialects/kafka/consumer/group.go#L94
https://github.com/jeroenrinzema/commander/blob/master/dialects/kafka/consumer/group.go#L89

**To Reproduce**
Steps to reproduce the behavior. Please include code examples:
1. Setup '...'
2. Emit event '....'
3. Await x seconds '....'

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Golang version

**Additional context**

**Comment by jeroenrinzema** [comment]
Hi, thank you very much for reporting this race condition.
