### ISSUE TITLE
data race

### ISSUE THREAD

**Issue by NOMORECOFFEE** [jeroenrinzema/commander#29]
**Describe the bug**
data race between close ready channel, create and select
https://github.com/jeroenrinzema/commander/blob/master/dialects/kafka/consumer/group.go#L67
we can receive new ready channel here (not closed)
https://github.com/jeroenrinzema/commander/blob/master/dialects/kafka/consumer/group.go#L56

**To Reproduce**
Steps to reproduce the behavior. Please include code examples:
1. Setup '...'
2. Emit event '....'
3. Await x seconds '....'

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Golang version

**Additional context**

**Comment by jeroenrinzema** [comment]
Thank you for pointing this out to me 👊. I have pushed a fix to master and will create a new release once I have thoroughly tested it. I will also try to push some unit tests for the Kafka dialect in the coming days.
